//Global information
#define NOTHX_NB_CARD 35
#define NOTHX_NB_PLAYERS_MAX 5

//Window parameter
#define NOTHX_FPS 25
#define NOTHX_SCREENRATIO_X 16
#define NOTHX_SCREENRATIO_Y 9
#define NOTHX_RESOLUTION_X 960
#define NOTHX_RESOLUTION_Y ((NOTHX_RESOLUTION_X*NOTHX_SCREENRATIO_Y)/NOTHX_SCREENRATIO_X)
#define NOTHX_TITLE "No Thanks! v1.0"
#define NOTHX_TILES_SIZE_X 128
#define NOTHX_TILES_SIZE_Y 128

#define NOTHX_RC_PATH "../resources/img/default"
